name: Best Practices Assignment - Testing on Staging

on:
  workflow_run:
    workflows:
      [
        "Best Practices Assignment - Automatically Deploy to Staging and Production",
      ]
    types:
      - completed

env:
  NODE_ENV: staging
  PROJECT_PATH: "ThePhasesOfCraftship/2_best_practice_first/deployment/assignment/end"
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  test-acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16

      - name: Install
        run: npm i
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Wait for 300 seconds
        run: sleep 300s
        shell: bash

      - name: Test (core e2e tests)
        run: npm run test:staging
        working-directory: ${{ env.PROJECT_PATH }}
